name: victoria
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1
# Flutter SDK version
environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.16
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.9
  http: ^1.2.1
  local_auth: ^2.2.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Assets configuration
  assets:
    - lib/assets/splashscreen.png
    - lib/assets/loginscreen.png
    - lib/assets/loginscreen1.png
    - lib/assets/otp.png
    - lib/assets/passwordreset.png
    - lib/assets/loginbio.png
    - lib/assets/settings.png

  # Material design
  uses-material-design: true
